name: Create and Push Nuget Package

on:
  push:
    branches:
      - main            # Trigger on push to the 'main' branch
      - 'release/*'     # Trigger on push to any branch matching 'release/*' (e.g., 'release/1.0', 'release/feature-x')
    paths-ignore:
    - '.github/workflows/**'      
  create:
    branches:
      - 'release/*'     # Trigger when a new branch matching 'release/*' is created. (Happens early in the release process, when the release branch is established.)
  release:
    types: [published]  # Trigger when a GitHub Release is published via the GitHub UI or API.. (Happens at the very end of the release process, when the official release is made public.)    

  workflow_dispatch:

jobs:
  job_1:
    name: Create Nuget Package
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v2
      
      - name: Download NuGet.exe
        run: curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe        

      - name: Restore dependencies
        run: ./nuget.exe restore Common/Common.sln -ConfigFile Common/nuget.config

      - name: Build
        run: |
            msbuild /p:Configuration=Release Common/Common.sln
            ls

      - name: Create Package
        shell: bash
        run: |
          cd Common
          REF="${GITHUB_REF}"
          if [[ "$REF" == "refs/heads/main" ]]; then
            nuget.exe pack Common.nuspec -version "1.0.1.0-dev.${GITHUB_RUN_NUMBER}"
          elif [[ "$REF" == refs/heads/release/* ]]; then
            nuget.exe pack Common.nuspec -version "1.0.1.0"
          fi          
          ls
  
      - name: Push Package
        run: |
          cd Common
          pwd
          ls
          dotnet nuget update source github --source "https://nuget.pkg.github.com/zawmyohtet2009/index.json" --username zawmyohtet2009 --password ${{ secrets.TOKEN }} --store-password-in-clear-text --configfile nuget.config
          dotnet nuget push common.*.nupkg --source "https://nuget.pkg.github.com/zawmyohtet2009/index.json" -k ${{ secrets.TOKEN }}
